### ISSUE TITLE
Host token information on the testnet home domain for Discoverablity and Meta information

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#1]
Host token information on the testnet home domain for [Discoverablity and Meta information](https://www.stellar.org/developers/guides/issuing-assets.html#discoverablity-and-meta-information) 
- [x] Add a `config/testnet/stellar.toml` to this repo
- [x] serve it on  `www3.threefold.io/.well-known/stellar.toml`
    - [x] Add it to the website's  github repo
    - [x] [Make sure the CORS header is set](https://github.com/threefoldfoundation/www_threefold.io_new/issues/155)
- [x] Add the home domain to the custom asset

**Comment by robvanmieghem** [comment]
Requires https://github.com/threefoldfoundation/www_threefold.io_new/issues/155
