### ISSUE TITLE
Create TFTA Issuers and publish meta info

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#105]
- [x] Issuers 
- [x] publish them on the main github readme
- [x] set homedomains on the stellar chain
- [x] adapt the stellar.toml files
- [x] publish them on the websites
  - [x] Updated in the repo
  - [x] [Deploy](https://github.com/threefoldfoundation/www_threefold.io_new/issues/192)
