### ISSUE TITLE
Unlock vested tokens

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/tft-stellar#394]
# Vesting Services

## Background / Description
Vesting services has been successfully created and running on v1.4.2. As a user i would like to be able to release vested TFT when requirement is met by agreement (end of june- $0.1 TFT average price)

## Specification

- Release locked TFTs from vested accounts monthly, when TFT average price is higher or equal than $0.1 on the particular month.

## User Story
Unvest locked TFTs from vested accounts

### Tickets

- [x]  Write a script to calculate the average monthly tft price #338 
https://github.com/threefoldfoundation/tft-stellar/tree/development_1.4.5/scripts/info

- [ ] return a list of free and vested amount of TFTs from the vesting service #389 
https://github.com/threefoldfoundation/tft-stellar/issues/389

- [ ] Create a feature on TF wallet to automatically unlock vested TFT [tfwallet-#246](https://github.com/threefoldtech/threefold_wallet/issues/246)

- [ ] Create a service on TFT stellar to accept the unvest the token based on the transaction request created by the  vested tf wallet accounts #390 

- [ ] Create a background app for the co-signers  to verify and sign the unvest transactions #391 

- [ ] optional (do a notification on TF wallet when token unvested) [tfwallet-#247](https://github.com/threefoldtech/threefold_wallet/issues/247)
