### ISSUE TITLE
Freetft faucet

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#59]
Website where you acquire 1000 FreeTFT's on 3bot connect login.
A user can only receive them once for now( this can be checked through the stellar network, no need for a seperate database).
It should be a package in https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages

It will be deployed in a threebot server  and users can browse to it and log in using threebot connect app when they want to receive the tokens

Propose to add a hash of the threebot id in the transaction to check if someone already got tokens or not

Open questions: 
- which address? First version: let the user paste it in an inputfield

TODO:
- [x] Better UI for the FreeTFT faucet #79 
- [x] anonymize the username in the faucet #64
- [x] Cannot deploy faucet frontend on the threebot  #78

**Comment by DylanVerstraete** [comment]
ready for deployment: https://github.com/threefoldfoundation/tft-stellar/pull/77
